### PR TITLE
Serve API error handling

### PR DESCRIPTION
**Pull request by Skemba**
Added fatal log on RPC loading failed.

### CODE REVIEW

**Comment by Skemba** [comment]
@tjayrush let me know if there's a reason for server to not exit if RPC loading failed and I'll change Fatalf to Printf.

**Comment by tjayrush** [comment]
> @tjayrush let me know if there's a reason for server to not exit if RPC loading failed and I'll change Fatalf to Printf.

I think I'd prefer that the server doesn't die, but it should also probably return an error response (which it may not currently do). If a front end is running against the server, and it dies, that would not be good.

**Comment by Skemba** [comment]
> If a front end is running against the server, and it dies, that would not be 

This runs only once when `chifra serve` is executed, so it would die right away, someone who started it would know right away. which might actually be the best behavior of a server, rather than it saying it's "running" while failing?

**Comment by tjayrush** [comment]
Sounds good. I’ll merge it now.

**Comment by tjayrush** [comment]
Thanks for this. Sorry it took so long to merge.

**Pull request merged**
