### PR TITLE
Adding links to buttons (Twitter…)

### PR DESCRIPTION
**Pull request by omahs**
Adding links to buttons (Twitter, Forks…)

### CODE REVIEW

**Comment by tjayrush** [comment]
Don't they already have links? I'm confused? You have square brackets inside of square backets, not?

**Comment by omahs** [comment]
Hi @tjayrush, at the moment those are just links to the button image, with the change it will go to the twitter page.

**Comment by tjayrush** [comment]
Are you in our discord? I think you get a POAP. It would be cool (if you care) to show the rest of the visitors to our discord how exciting it is to get POAPs -- plus it would be interesting to see how it works.

**Comment by omahs** [comment]
I'm not on the Discord but I'll join and explain a little about the POAP process 😃

**Pull request merged**
