### PR TITLE
changing condition of adding erc20 token candidates

### PR DESCRIPTION
**Pull request by artur-jablonski**

### CODE REVIEW

**Comment by tjayrush** [comment]
Thanks for this PR. This one-liner was a bit too specific for a single topic, so I extended it a bit to be more general. I added it with a test case to this PR https://github.com/TrueBlocks/trueblocks-core/pull/2173 (which has an additional test). I'll close this PR. Thanks for it.

**Comment by artur-jablonski** [comment]
> Thanks for this PR. This one-liner was a bit too specific for a single topic, so I extended it a bit to be more general. I added it with a test case to this PR #2173 (which has an additional test). I'll close this PR. Thanks for it.

I scanned through the changes. My understanding is that the "statements" in trueblocks are all about transfer of value. If there's no transfer of value there's no statement. Correct? The only event that indicates there was any transfer of value of ERC20 from the spec (https://ethereum.org/en/developers/docs/standards/tokens/erc-20/) is the Transfer event:

```
event Transfer(address indexed _from, address indexed _to, uint256 _value)
event Approval(address indexed _owner, address indexed _spender, uint256 _value)
```

so I thought this should be the only event to look for. `Approval` is not transfering value nor do (I assume) other events from `tokenRelated` array that I am not sure exactly what they are (which standard they come from):

```
make_pair("0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
              true),  // Transfer(address from, address to, uint256 value)
    make_pair("0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
              true),  // Approval(address owner, address spender, uint256 value)
    make_pair("0xd4735d920b0f87494915f556dd9b54c8f309026070caea5c737245152564d266",
              true),  // Transfer(bytes32 node, address owner)
    make_pair("0x30385c845b448a36257a6a1716e6ad2e1bc2cbe333cde1e69fe849ad6511adfe",
              true),  // Minted(address,uint256)
};
```

Perhaps I am missin gsth

**Comment by tjayrush** [comment]
>  If there's no transfer of value there's no statement. Correct?

Not quite.

You're right that many of these `isTokenRelated` topics and four-bytes are not standard.

But I'm trying to reconcile everything, so standards, while super nice, aren't enough.

I've not seen a transfer of value during an Approval, but it's possible.

I have seen it in the other things included in `isTokenRelated`.

My thought is to be 'over-inclusive' and if we "reconcile" a transaction that has no value transfer that's better than not reconciling one that does.

I do this frequently -- especially in the indexing and bloom filtering on the assumption it's easier to filter out data later in the pipeline than to never have had the data to being with.

**Comment by artur-jablonski** [comment]
> > If there's no transfer of value there's no statement. Correct?
> 
> Not quite.
> 
> You're right that many of these `isTokenRelated` topics and four-bytes are not standard.
> 
> But I'm trying to reconcile everything, so standards, while super nice, aren't enough.
> 
> I've not seen a transfer of value during an Approval, but it's possible.
> 
> I have seen it in the other things included in `isTokenRelated`.
> 
> My thought is to be 'over-inclusive' and if we "reconcile" a transaction that has no value transfer that's better than not reconciling one that does.
> 
> I do this frequently -- especially in the indexing and bloom filtering on the assumption it's easier to filter out data later in the pipeline than to never have had the data to being with.

Got ya. 

On the flip side being overinclusive can result in poorer performance but I think I understand where you're coming from with this approach. In any case I think the logic as it is now is way better than before so it's a win :muscle:

**Comment by tjayrush** [comment]
Once we get to GoLang, we can optimize, but by then, I hope, we have solid tests (especially surrounding reconciliation). Tests make optimizations much, much easier so we're not worried about breaking things.

On that note, I tried to add your test to the regular testing, but something was broken. One thing that would be good, while we're waiting for the GoLang code, would be to enhance the test cases by finding non-reconciling examples. (For test cases, it's always better to find small accounts with errors -- otherwise, the testing gets super slow.)

**Comment by tjayrush** [comment]
Thanks so much for your thoughts, Artur. I appreciate them a lot.

**Comment by artur-jablonski** [comment]
> On that note, I tried to add your test to the regular testing, but something was broken.

Hmmm, I think this PR didn't fix anything in reconciliation logic but rather improved performance by not including all log entries as tokens when just one of them was token related (which was the logic before my PR), so there are no tests to add/remove/adjust. Maybe you're referring to the other PR I opened for partial (intra-block) reconciliation of ERC20? (#2162)

**Comment by tjayrush** [comment]
No. This one. I tried to add the test, but it was failing, so I had to turn it off (making it say `local` turns it off by the way).

Help me simplify this a bit (if you’re not burned out…)


Send me the exact command you use and the exact respected results. Hopefully, it doesn’t work on a release prior to the fix, but it does after the fix.

Sorry if you’ve already done that, I’ve lost the thread a bit….

I will

1. run it against an old release to make sure it fails
2. move to the latest release
3. work on it until the test passes
4. Push new code if I need to.

I’d really like to capture a non-reconciling token transaction if I can.

Of course, I understand if I’m asking too much, and thanks so much for all your help so far.

Cheers.

**Comment by artur-jablonski** [comment]
So there was no non-reconciling token in this case. I found the issue by reading the code. I explained it here: https://github.com/TrueBlocks/trueblocks-core/issues/2164#issuecomment-1152442993.

So I would expect that this PR would simply not break any tests. If it does, then I can have a look why. But esentially this is an optimisation.

**Pull request closed without merging**
