### PR TITLE
Websockets server for tbServer

### PR DESCRIPTION
**Pull request by dszlachta**
This implements WebSockets server inside tbServer.
Sending progress messages in Node.js API-compatible format is supported (Action has to be ProgressMessage and CommandProgress has to be passed as message.progress)

### CODE REVIEW

**Comment by tjayrush** [comment]
Thanks for this.

1) You can re-merge with the `develop` branch?
2) When I try to run this, it hangs the server

My guess is that stderr is getting over-burdened. I wonder if it's possible to not 'scan' the output of stderr and just pass it through to the server's stderr (ignoring websocket code for a second).

**Review by teetee-make — APPROVED** [review]

**Review by teetee-make — APPROVED** [review]

**Review by teetee-make — APPROVED** [review]

**Review by teetee-make — APPROVED** [review]

**Comment by tjayrush** [comment]
Has there been any progress on this? I'd like to close it as soon as possible.

I tried to get it working myself -- no luck. When I try to run it, I get:

```
Error while sending message, dropping connectionwrite tcp [::1]:8080->[::1]:62410: write: broken pipe
```

Not sure what the status is.

**Comment by dszlachta** [comment]
I have rebased my branch with `develop`, so it is ready to be merged there when you think it is ready.

Could you write when this error happens? Which command are you trying to run? It may happen that a connection is dropped, just like with standard HTTP request.  The important thing is that the server should not exit.

This is how it looks like on my computer, you can see stderr being printed:
Zrzut ekranu 2021-03-3 o 22 15 50

**Comment by dszlachta** [comment]
Ah, I see now. This happens when a connection has disconnected - it should have been removed from connection pool, but it is still there. Will push fix shortly

**Comment by dszlachta** [comment]
The issue should be fixed now

**Comment by tjayrush** [comment]
This part seems to be working. Merging now.

**Pull request merged**
