### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Comment by tjayrush** [comment]
Thanks! If you can figure it out, you should be able to get a GitPoap. I'm sorry, I forget how to help you there, but I'd love a PR to the documentation website showing people how.

Merging now.

**Comment by tjayrush** [comment]
Actually, I'm just noticing that it has conflicts. Can you fix them? Also - make the PR against develop, please.

Thanks.

**Comment by omahs** [comment]
@tjayrush I don't know the reason of this conflict, is it possible to re-run the actions? (seems I can't re-run myself)

**Comment by tjayrush** [comment]
You had to rebase. I did it. Merging now.

**Pull request merged**
